version: 'version: 3.7'

services:
  mongo: 
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: giovani
      MONGO_INITDB_ROOT_PASSWORD: giovani

mongo-express:
  image: mongo-express
  ports:
    - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: giovani
    ME_CONFIG_MONGODB_ADMINPASSWORD: giovani
    ME_CONFIG_MONGODB_URL: mongodb://localhost:27017